### ISSUE TITLE
`aws-lite` should respect env var credentials definitions regardless of presence of `.aws/credentials`

### ISSUE THREAD

**Issue by andybee** [aws-lite/aws-lite#175]
### Describe the problem underlying the enhancement request

If you provide env var credentials to the Node.js script that utilises `aws-lite`, but the same environment happens to have a `.aws/credentials` file, the library will try and use that with a placeholder profile name of `default` and fail if such a profile does not exist. If it does exist, presumably it uses that profile instead of the credentials provided as env vars?

### Describe the solution you'd like (if any)

Ideally, the presence of environment variables should override looking for `.aws/credentials`.

### Describe alternative solutions you've considered

I can work around for this by reading the env vars myself and supplying them to the client.

**Comment by andybee** [comment]
Sorry, I didn't leave this bug report with a particularly easy/useful example.

I've thrown together a very quick and dirty example implementation: https://github.com/andybee/aws-lite-credential-demo

1. Pull the repo
2. `npm install`
3. Then assuming `~/.aws/credentials` exists and doesn't have a `default` entry, try the following:

```
AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar node index.mjs
```

I receive the error:

```
/Users/andy/Desktop/test/node_modules/@aws-lite/client/src/lib/index.js:144
    else throw ReferenceError(`Profile not found: ${profile}`)
               ^

ReferenceError: Profile not found: default
    at loadAwsConfig (/Users/andy/Desktop/test/node_modules/@aws-lite/client/src/lib/index.js:144:16)
    at async getEndpoint (/Users/andy/Desktop/test/node_modules/@aws-lite/client/src/config/get-endpoint.js:13:48)
    at async awsLite (/Users/andy/Desktop/test/node_modules/@aws-lite/client/src/index.js:42:18)
    at async file:///Users/andy/Desktop/test/index.mjs:3:13
```

I'd expect AWS Lite to use the creds passed, but instead it looks like it finds `~/.aws/credentials` and then gets stumped by not having a `default` profile.

**Comment by filmaj** [comment]
Yeah I have the same issue. On my work laptop, where I don't have a `default` profile defined, I can't even run the tests locally in the aws-lite repo because they assume you have one defined. I can repro Andy's issue above on my personal laptop by renaming the `default` profile to `default1` in my `~/.aws/config` and `~/.aws/credentials` files.

On `main`, if if you don't have `default` profile present and you run the tests, you'll see the following failures:

```console
npm t
...
Configuration - basic config
    ✗ [5198] ReferenceError: Profile not found: default
        Expected error to be falsy
    ✗ [5199] plan != count
        Explicit fail

Configuration - plugin loading
    ✗ [5200] ReferenceError: Profile not found: default
        Expected error to be falsy
    ✗ [5201] plan != count
        Explicit fail

...
Testing - credentials
    ✗ [5588] ReferenceError: Profile not found: default
        Expected error to be falsy
    ✗ [5589] plan != count
        Explicit fail
...
Failed tests: There were 6 failures

    ✗ [5198] ReferenceError: Profile not found: default
    ✗ [5199] plan != count
    ✗ [5200] ReferenceError: Profile not found: default
    ✗ [5201] plan != count
    ✗ [5588] ReferenceError: Profile not found: default
    ✗ [5589] plan != count

total:     5729
passing:   5723
failing:   6
```

**Comment by filmaj** [comment]
The issue is not in credential retrieval but in `getEndpoint`, which executes before credential retrieval. Andy's stack trace above demonstrates this. It has logic to read credentials (via `loadAwsConfig`). If you don't set an `AWS_PROFILE`, aws-lite falls back to using `default`. `loadAwsConfig` leverages that assumption.
